name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: OzkanBirak
          outputs: dist/snake.svg

      - name: Push Snake Animation to Output Folder
        run: |
          mkdir -p output
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
